// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBWpuFAqh2JDG9XXraBdgAnmgfLmi3Zg',
    appId: '1:249114658216:web:5179bb1415b0ad4b40899d',
    messagingSenderId: '249114658216',
    projectId: 'tampay-6154b',
    authDomain: 'tampay-6154b.firebaseapp.com',
    storageBucket: 'tampay-6154b.firebasestorage.app',
    measurementId: 'G-GVWHVYBF0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19fF87gKVIFD78QBC53Gi0O-yf49nXqE',
    appId: '1:249114658216:android:4647b69d8146b5a740899d',
    messagingSenderId: '249114658216',
    projectId: 'tampay-6154b',
    storageBucket: 'tampay-6154b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOchcD-fwscRAMg7oXLXwkFxe7rYMBks',
    appId: '1:249114658216:ios:690ade86ff98aa7840899d',
    messagingSenderId: '249114658216',
    projectId: 'tampay-6154b',
    storageBucket: 'tampay-6154b.firebasestorage.app',
    iosBundleId: 'com.example.applicationweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkOchcD-fwscRAMg7oXLXwkFxe7rYMBks',
    appId: '1:249114658216:ios:690ade86ff98aa7840899d',
    messagingSenderId: '249114658216',
    projectId: 'tampay-6154b',
    storageBucket: 'tampay-6154b.firebasestorage.app',
    iosBundleId: 'com.example.applicationweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnBWpuFAqh2JDG9XXraBdgAnmgfLmi3Zg',
    appId: '1:249114658216:web:e90ef198960b0d1040899d',
    messagingSenderId: '249114658216',
    projectId: 'tampay-6154b',
    authDomain: 'tampay-6154b.firebaseapp.com',
    storageBucket: 'tampay-6154b.firebasestorage.app',
    measurementId: 'G-SNXQH1LQK3',
  );
}
